id: A334E4464
title: Prayer for the Swift Rebirth of Yangthang Rinpoche
type: translation
pechas:
- I68642492
- I28D47704
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:25.859602
  last_modified_at: 2023-01-04 11:55:25.859622
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I68642492/35D6: 5C6F
  I28D47704/622B: 5C6F
